### ISSUE TITLE
Alternative to Docker?

### ISSUE THREAD

**Issue by qsengshu** [lgsvl/lanefollowing#1]
Dear Team of the LGSVL Project,

Is there an alternative to Docker? Or is it necessary to use it? Is it possible to use the cpu instead of gpu?
About us:
We are Researchers from University RWTH Aachen Germany. Me and my PhD Supervisor are working on an big autnomous driving project about self driving busses.

Best Regards,
qsengshu

**Comment by daviduhm** [comment]
We've just pushed a new [commit](https://github.com/lgsvl/lanefollowing/commit/26421382188df16d98e4f3152f7a998676d4b86d) to support running Tensorflow on CPU. You can pull the latest and run `docker-compose up drive_cpu` or `docker-compose up drive_visual_cpu` to launch the model without GPU.

As for Docker, technically it is not a mandatory requirement, but it is highly recommended because of its simplifying configuration. In order to run the lane following model alongside LGSVL Simulator, you are required to have many dependencies such as ROS2, rosbridge, python, tensorflow, keras, sklearn, cuda, and etc. You can check [Dockerfile](https://github.com/lgsvl/lanefollowing/blob/master/Dockerfile) and [docker-compose](https://github.com/lgsvl/lanefollowing/blob/master/docker-compose.yml) and try setting up all dependencies on your host machine, but again, it would be much simpler if you use Docker as the docker image already have those dependencies installed.

Thank you for your interests in using the lane following model and LGSVL Simulator. Please let us know if you have any questions or need further assistance.

**Comment by daviduhm** [comment]
Please note that [this commit](https://github.com/lgsvl/lanefollowing/commit/26421382188df16d98e4f3152f7a998676d4b86d) only hides GPU devices from CUDA so you can run tensorflow on CPU only (without GPU). But, it is still required to run with nvidia runtime since the tensorflow inside the docker image is built with GPU enabled.

If you are trying to run it without Docker, make sure that you install tensorflow version with CPU only. We are also planning to publish another Docker image to support CPU only mode soon.

**Comment by qsengshu** [comment]
Thanks for your help David. We appreciate it very much!

Greetings from Germany!
